# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6540814162a49330a5e0b59bbb9b2b17b8c317c9b5f6dd67e4cd72360d1670655cab5dd4850a60ac915503346b5a97705733ed13356660a4447bf7e2b00d607d

test:
  secret_key_base: 627fe5ec1e300d14c8e8fc6e1a7c7257f48060e4bb345b87727527f0eaa99b5b1917b5a7905d7d780f8e7f67852a06ad99fcf7b01805ffefa0567deab5e5b85a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
